services:
  blueos-slam:
    image: andrewkwolek3/blueos-blueos-slam:main
    container_name: blueos-slam
    # network_mode: host
    ports:
      - "9050:9050"
    restart: unless-stopped
    environment:
      - BLUEOS=True