services:
  blueos-slam:
    build:
      context: .  # Build the image from the current directory
      dockerfile: Dockerfile  # Specify the Dockerfile if it's not the default 'Dockerfile'
    image: andrewkwolek3/blueos-blueos-slam:main  # Name of the image you want to build
    container_name: blueos-slam
    ports:
      - "9050:9050"
      - "14550:14550/udp"
      - "5600:5600/udp"
    restart: unless-stopped
    environment:
      - BLUEOS=True
