services:
  blueos-slam:
    image: andrewkwolek3/blueos-blueos-slam:main
    container_name: blueos-slam
    # network_mode: host
    ports:
      - "9050:9050"
      - "14550:14550/udp"
      - "5600:5600/udp"
    restart: unless-stopped
    environment:
      - BLUEOS=True